import { describe, expect, test } from 'vitest';
import { isInteractive, type TagName } from '../../src/index.js';
import { checkAllTagsTested, checkTestAndTagName } from './../helpers';

// add <div tabindex=0>
// add <div role="button" tabindex=0>

describe('isInteractive', () => {
  const tests: [string, { given: Parameters<typeof isInteractive>; want: ReturnType<typeof isInteractive> }][] = [
    ['a', { given: [{ tagName: 'a' }], want: false }],
    ['a[ref=#]', { given: [{ tagName: 'a', attributes: { href: '#' } }], want: true }],
    ['area (no href)', { given: [{ tagName: 'area' }], want: false }],
    ['area[href=#]', { given: [{ tagName: 'area', attributes: { href: '#' } }], want: true }],
    ['abbr', { given: [{ tagName: 'abbr' }], want: false }],
    ['address', { given: [{ tagName: 'address' }], want: false }],
    ['article', { given: [{ tagName: 'article' }], want: false }],
    ['aside', { given: [{ tagName: 'aside' }], want: false }],
    ['audio', { given: [{ tagName: 'audio' }], want: false }],
    ['b', { given: [{ tagName: 'b' }], want: false }],
    ['base', { given: [{ tagName: 'base' }], want: false }],
    ['bdi', { given: [{ tagName: 'bdi' }], want: false }],
    ['bdo', { given: [{ tagName: 'bdo' }], want: false }],
    ['blockquote', { given: [{ tagName: 'blockquote' }], want: false }],
    ['body', { given: [{ tagName: 'body' }], want: false }],
    ['br', { given: [{ tagName: 'br' }], want: false }],
    ['button', { given: [{ tagName: 'button' }], want: true }],
    ['button[disabled]', { given: [{ tagName: 'button', attributes: { disabled: true } }], want: false }],
    ['button[aria-disabled]', { given: [{ tagName: 'button', attributes: { 'aria-disabled': true } }], want: false }],
    ['canvas', { given: [{ tagName: 'canvas' }], want: false }],
    ['caption', { given: [{ tagName: 'caption' }], want: false }],
    ['cite', { given: [{ tagName: 'cite' }], want: false }],
    ['code', { given: [{ tagName: 'code' }], want: false }],
    ['col', { given: [{ tagName: 'col' }], want: false }],
    ['colgroup', { given: [{ tagName: 'colgroup' }], want: false }],
    ['data', { given: [{ tagName: 'data' }], want: false }],
    ['datalist', { given: [{ tagName: 'datalist' }], want: true }],
    ['dd', { given: [{ tagName: 'dd' }], want: false }],
    ['del', { given: [{ tagName: 'del' }], want: false }],
    ['details', { given: [{ tagName: 'details' }], want: false }],
    ['dfn', { given: [{ tagName: 'dfn' }], want: false }],
    ['dialog', { given: [{ tagName: 'dialog' }], want: true }],
    ['div', { given: [{ tagName: 'div' }], want: false }],
    ['div[role=button]', { given: [{ tagName: 'div', attributes: { role: 'button' } }], want: false }],
    ['div[tabindex=0]', { given: [{ tagName: 'div', attributes: { role: 'button', tabindex: 0 } }], want: true }],
    ['div[role=button,tabindex=0]', { given: [{ tagName: 'div', attributes: { tabindex: 0 } }], want: false }],
    ['dl', { given: [{ tagName: 'dl' }], want: false }],
    ['dt', { given: [{ tagName: 'dt' }], want: false }],
    ['em', { given: [{ tagName: 'em' }], want: false }],
    ['embed', { given: [{ tagName: 'embed' }], want: false }],
    ['fieldset', { given: [{ tagName: 'fieldset' }], want: false }],
    ['figcaption', { given: [{ tagName: 'figcaption' }], want: false }],
    ['figure', { given: [{ tagName: 'figure' }], want: false }],
    ['form', { given: [{ tagName: 'form' }], want: false }],
    ['footer', { given: [{ tagName: 'footer' }], want: false }],
    ['h1', { given: [{ tagName: 'h1' }], want: false }],
    ['h2', { given: [{ tagName: 'h2' }], want: false }],
    ['h3', { given: [{ tagName: 'h3' }], want: false }],
    ['h4', { given: [{ tagName: 'h4' }], want: false }],
    ['h5', { given: [{ tagName: 'h5' }], want: false }],
    ['h6', { given: [{ tagName: 'h6' }], want: false }],
    ['head', { given: [{ tagName: 'head' }], want: false }],
    ['header', { given: [{ tagName: 'header' }], want: false }],
    ['hgroup', { given: [{ tagName: 'hgroup' }], want: false }],
    ['hr', { given: [{ tagName: 'hr' }], want: false }],
    ['hr[tabindex=0]', { given: [{ tagName: 'hr', attributes: { tabindex: 0 } }], want: false }],
    ['hr[aria-valuenow=10]', { given: [{ tagName: 'hr', attributes: { 'aria-valuenow': 10 } }], want: false }],
    [
      'hr[tabindex=0,aria-valuenow=10]',
      { given: [{ tagName: 'hr', attributes: { tabindex: 0, 'aria-valuenow': 10 } }], want: true },
    ],
    ['html', { given: [{ tagName: 'html' }], want: false }],
    ['i', { given: [{ tagName: 'i' }], want: false }],
    ['iframe', { given: [{ tagName: 'iframe' }], want: false }],
    ['img', { given: [{ tagName: 'img' }], want: false }],
    ['input[type=button]', { given: [{ tagName: 'input', attributes: { type: 'button' } }], want: true }],
    ['input[type=checkbox]', { given: [{ tagName: 'input', attributes: { type: 'checkbox' } }], want: true }],
    ['input[type=color]', { given: [{ tagName: 'input', attributes: { type: 'color' } }], want: true }],
    ['input[type=date]', { given: [{ tagName: 'input', attributes: { type: 'date' } }], want: true }],
    [
      'input[type=datetime-local]',
      { given: [{ tagName: 'input', attributes: { type: 'datetime-local' } }], want: true },
    ],
    ['input[type=email]', { given: [{ tagName: 'input', attributes: { type: 'email' } }], want: true }],
    ['input[type=file]', { given: [{ tagName: 'input', attributes: { type: 'file' } }], want: true }],
    ['input[type=hidden]', { given: [{ tagName: 'input', attributes: { type: 'hidden' } }], want: false }],
    ['input[type=image]', { given: [{ tagName: 'input', attributes: { type: 'image' } }], want: true }],
    ['input[type=month]', { given: [{ tagName: 'input', attributes: { type: 'month' } }], want: true }],
    ['input[type=number]', { given: [{ tagName: 'input', attributes: { type: 'number' } }], want: true }],
    ['input[type=password]', { given: [{ tagName: 'input', attributes: { type: 'password' } }], want: true }],
    ['input[type=radio]', { given: [{ tagName: 'input', attributes: { type: 'radio' } }], want: true }],
    ['input[type=range]', { given: [{ tagName: 'input', attributes: { type: 'range' } }], want: true }],
    ['input[type=reset]', { given: [{ tagName: 'input', attributes: { type: 'reset' } }], want: true }],
    ['input[type=search]', { given: [{ tagName: 'input', attributes: { type: 'search' } }], want: true }],
    ['input[type=shrek]', { given: [{ tagName: 'input', attributes: { type: 'shrek' } }], want: true }],
    ['input[type=submit]', { given: [{ tagName: 'input', attributes: { type: 'submit' } }], want: true }],
    ['input[type=tel]', { given: [{ tagName: 'input', attributes: { type: 'tel' } }], want: true }],
    ['input[type=text]', { given: [{ tagName: 'input', attributes: { type: 'text' } }], want: true }],
    ['input[type=text]', { given: [{ tagName: 'input', attributes: { type: 'text', disabled: true } }], want: false }],
    [
      'input[type=text]',
      { given: [{ tagName: 'input', attributes: { type: 'text', 'aria-disabled': true } }], want: false },
    ],
    ['input[type=time]', { given: [{ tagName: 'input', attributes: { type: 'time' } }], want: true }],
    ['input[type=url]', { given: [{ tagName: 'input', attributes: { type: 'url' } }], want: true }],
    ['input[type=week]', { given: [{ tagName: 'input', attributes: { type: 'week' } }], want: true }],
    ['input (list)', { given: [{ tagName: 'input', attributes: { list: 'things' } }], want: true }],
    [
      'input[type=email] (list)',
      { given: [{ tagName: 'input', attributes: { type: 'email', list: 'emails' } }], want: true },
    ],
    ['ins', { given: [{ tagName: 'ins' }], want: false }],
    ['kbd', { given: [{ tagName: 'kbd' }], want: false }],
    ['label', { given: [{ tagName: 'label' }], want: false }],
    ['legend', { given: [{ tagName: 'legend' }], want: false }],
    ['li', { given: [{ tagName: 'li' }], want: false }],
    ['link', { given: [{ tagName: 'link' }], want: false }],
    ['main', { given: [{ tagName: 'main' }], want: false }],
    ['map', { given: [{ tagName: 'map' }], want: false }],
    ['mark', { given: [{ tagName: 'mark' }], want: false }],
    ['math', { given: [{ tagName: 'math' }], want: false }],
    ['menu', { given: [{ tagName: 'menu' }], want: false }],
    ['menu[role=tree]', { given: [{ tagName: 'menu', attributes: { role: 'tree' } }], want: false }],
    [
      'menu[tabindex=0,role=tree]',
      { given: [{ tagName: 'menu', attributes: { tabindex: 0, role: 'tree' } }], want: true },
    ],
    ['meta', { given: [{ tagName: 'meta' }], want: false }],
    ['meter', { given: [{ tagName: 'meter' }], want: false }],
    ['nav', { given: [{ tagName: 'nav' }], want: false }],
    ['noscript', { given: [{ tagName: 'noscript' }], want: false }],
    ['object', { given: [{ tagName: 'object' }], want: false }],
    ['ol', { given: [{ tagName: 'ol' }], want: false }],
    ['optgroup', { given: [{ tagName: 'optgroup' }], want: false }],
    ['option', { given: [{ tagName: 'option' }], want: true }],
    ['output', { given: [{ tagName: 'output' }], want: false }],
    ['p', { given: [{ tagName: 'p' }], want: false }],
    ['picture', { given: [{ tagName: 'picture' }], want: false }],
    ['pre', { given: [{ tagName: 'pre' }], want: false }],
    ['progress', { given: [{ tagName: 'progress' }], want: true }],
    ['q', { given: [{ tagName: 'q' }], want: false }],
    ['rp', { given: [{ tagName: 'rp' }], want: false }],
    ['rt', { given: [{ tagName: 'rt' }], want: false }],
    ['ruby', { given: [{ tagName: 'ruby' }], want: false }],
    ['s', { given: [{ tagName: 's' }], want: false }],
    ['samp', { given: [{ tagName: 'samp' }], want: false }],
    ['script', { given: [{ tagName: 'script' }], want: false }],
    ['search', { given: [{ tagName: 'search' }], want: false }],
    ['section', { given: [{ tagName: 'section' }], want: false }],
    ['select', { given: [{ tagName: 'select' }], want: true }],
    ['select[size=2]', { given: [{ tagName: 'select', attributes: { size: 2 } }], want: true }],
    ['select[multiple]', { given: [{ tagName: 'select', attributes: { multiple: true } }], want: true }],
    ['slot', { given: [{ tagName: 'slot' }], want: false }],
    ['small', { given: [{ tagName: 'small' }], want: false }],
    ['source', { given: [{ tagName: 'source' }], want: false }],
    ['span', { given: [{ tagName: 'span' }], want: false }],
    ['strong', { given: [{ tagName: 'strong' }], want: false }],
    ['style', { given: [{ tagName: 'style' }], want: false }],
    ['sub', { given: [{ tagName: 'sub' }], want: false }],
    ['summary', { given: [{ tagName: 'summary' }], want: false }],
    ['sup', { given: [{ tagName: 'sup' }], want: false }],
    ['svg', { given: [{ tagName: 'svg' }], want: false }],
    ['table', { given: [{ tagName: 'table' }], want: false }],
    ['tbody', { given: [{ tagName: 'tbody' }], want: false }],
    ['td', { given: [{ tagName: 'td' }], want: false }],
    ['td[role=gridcell]', { given: [{ tagName: 'td', attributes: { role: 'gridcell' } }], want: false }],
    [
      'td[tabindex=0,role=gridcell]',
      { given: [{ tagName: 'td', attributes: { tabindex: 0, role: 'gridcell' } }], want: true },
    ],
    [
      'td[tabindex=0] (grid descendant)',
      {
        given: [{ tagName: 'td' }, { ancestors: [{ tagName: 'table', attributes: { tabindex: 0, role: 'grid' } }] }],
        want: true,
      },
    ],
    [
      'td[tabindex=0] (treegrid descendant)',
      {
        given: [
          { tagName: 'td', attributes: { tabindex: 0 } },
          { ancestors: [{ tagName: 'table', attributes: { role: 'treegrid' } }] },
        ],
        want: true,
      },
    ],
    ['template', { given: [{ tagName: 'template' }], want: false }],
    ['textarea', { given: [{ tagName: 'textarea' }], want: true }],
    ['tfoot', { given: [{ tagName: 'tfoot' }], want: false }],
    ['th', { given: [{ tagName: 'th' }], want: false }],
    ['th', { given: [{ tagName: 'th', attributes: { scope: 'row' } }], want: false }],
    ['thead', { given: [{ tagName: 'thead' }], want: false }],
    ['time', { given: [{ tagName: 'time' }], want: false }],
    ['title', { given: [{ tagName: 'title' }], want: false }],
    ['tr', { given: [{ tagName: 'tr' }], want: false }],
    ['tr[tabindex=0]', { given: [{ tagName: 'tr', attributes: { tabindex: 0 } }], want: false }],
    [
      'tr[tabindex=0] (grid descendant)',
      {
        given: [
          { tagName: 'tr', attributes: { tabindex: 0 } },
          { ancestors: [{ tagName: 'table', attributes: { role: 'grid' } }] },
        ],
        want: false,
      },
    ],
    [
      'tr[tabindex=0] (treegrid descendant)',
      {
        given: [
          { tagName: 'tr', attributes: { tabindex: 0 } },
          { ancestors: [{ tagName: 'table', attributes: { role: 'treegrid' } }] },
        ],
        want: false,
      },
    ],
    ['track', { given: [{ tagName: 'track' }], want: false }],
    ['u', { given: [{ tagName: 'u' }], want: false }],
    ['ul', { given: [{ tagName: 'ul' }], want: false }],
    ['var', { given: [{ tagName: 'var' }], want: false }],
    ['video', { given: [{ tagName: 'video' }], want: false }],
    ['wbr', { given: [{ tagName: 'wbr' }], want: false }],

    // Custom elements
    ['custom-element', { given: [{ tagName: 'custom-element' as TagName }], want: false }],
    [
      'custom-element[role=button]',
      { given: [{ tagName: 'custom-element' as TagName, attributes: { role: 'button' } }], want: false },
    ],
    [
      'custom-element[tabindex=0]',
      { given: [{ tagName: 'custom-element' as TagName, attributes: { tabindex: 0 } }], want: false },
    ],
    [
      'custom-element[role=button,tabindex=0]',
      { given: [{ tagName: 'custom-element' as TagName, attributes: { role: 'button', tabindex: 0 } }], want: true },
    ],

    // SVG
    ['svg', { given: [{ tagName: 'svg' }], want: false }],
    ['svg[role=button]', { given: [{ tagName: 'svg', attributes: { role: 'button' } }], want: false }],
    ['svg[tabindex=0]', { given: [{ tagName: 'svg', attributes: { tabindex: 0 } }], want: false }],
    [
      'svg[role=button,tabindex=0]',
      { given: [{ tagName: 'svg', attributes: { role: 'button', tabindex: 0 } }], want: true },
    ],
    ['animate', { given: [{ tagName: 'animate' }], want: false }],
    ['animate[role=button]', { given: [{ tagName: 'animate', attributes: { role: 'button' } }], want: false }],
    ['animate[tabindex=0]', { given: [{ tagName: 'animate', attributes: { tabindex: 0 } }], want: false }],
    // <animate> should NEVER be interactive
    [
      'animate[role=button,tabindex=0]',
      { given: [{ tagName: 'animate', attributes: { role: 'button', tabindex: 0 } }], want: false },
    ],
    ['animateMotion', { given: [{ tagName: 'animateMotion' }], want: false }],
    ['animateTransform', { given: [{ tagName: 'animateTransform' }], want: false }],
    ['circle', { given: [{ tagName: 'circle' }], want: false }],
    ['circle[role=button]', { given: [{ tagName: 'circle', attributes: { role: 'button' } }], want: false }],
    ['circle[tabindex=0]', { given: [{ tagName: 'circle', attributes: { tabindex: 0 } }], want: false }],
    [
      'circle[role=button,tabindex=0]',
      { given: [{ tagName: 'circle', attributes: { role: 'button', tabindex: 0 } }], want: true },
    ],
    ['clipPath', { given: [{ tagName: 'clipPath' }], want: false }],
    ['defs', { given: [{ tagName: 'defs' }], want: false }],
    ['desc', { given: [{ tagName: 'desc' }], want: false }],
    ['ellipse', { given: [{ tagName: 'ellipse' }], want: false }],
    ['feBlend', { given: [{ tagName: 'feBlend' }], want: false }],
    ['feColorMatrix', { given: [{ tagName: 'feColorMatrix' }], want: false }],
    ['feComponentTransfer', { given: [{ tagName: 'feComponentTransfer' }], want: false }],
    ['feComposite', { given: [{ tagName: 'feComposite' }], want: false }],
    ['feConvolveMatrix', { given: [{ tagName: 'feConvolveMatrix' }], want: false }],
    ['feDiffuseLighting', { given: [{ tagName: 'feDiffuseLighting' }], want: false }],
    ['feDisplacementMap', { given: [{ tagName: 'feDisplacementMap' }], want: false }],
    ['feDistantLight', { given: [{ tagName: 'feDistantLight' }], want: false }],
    ['feDropShadow', { given: [{ tagName: 'feDropShadow' }], want: false }],
    ['feFlood', { given: [{ tagName: 'feFlood' }], want: false }],
    ['feFuncA', { given: [{ tagName: 'feFuncA' }], want: false }],
    ['feFuncB', { given: [{ tagName: 'feFuncB' }], want: false }],
    ['feFuncG', { given: [{ tagName: 'feFuncG' }], want: false }],
    ['feFuncR', { given: [{ tagName: 'feFuncR' }], want: false }],
    ['feGaussianBlur', { given: [{ tagName: 'feGaussianBlur' }], want: false }],
    ['feImage', { given: [{ tagName: 'feImage' }], want: false }],
    ['feMerge', { given: [{ tagName: 'feMerge' }], want: false }],
    ['feMergeNode', { given: [{ tagName: 'feMergeNode' }], want: false }],
    ['feMorphology', { given: [{ tagName: 'feMorphology' }], want: false }],
    ['feOffset', { given: [{ tagName: 'feOffset' }], want: false }],
    ['fePointLight', { given: [{ tagName: 'fePointLight' }], want: false }],
    ['feSpecularLighting', { given: [{ tagName: 'feSpecularLighting' }], want: false }],
    ['feSpotLight', { given: [{ tagName: 'feSpotLight' }], want: false }],
    ['feTile', { given: [{ tagName: 'feTile' }], want: false }],
    ['feTurbulence', { given: [{ tagName: 'feTurbulence' }], want: false }],
    ['filter', { given: [{ tagName: 'filter' }], want: false }],
    ['foreignObject', { given: [{ tagName: 'foreignObject' }], want: false }],
    ['g', { given: [{ tagName: 'g' }], want: false }],
    ['image', { given: [{ tagName: 'image' }], want: false }],
    ['line', { given: [{ tagName: 'line' }], want: false }],
    ['linearGradient', { given: [{ tagName: 'linearGradient' }], want: false }],
    ['marker', { given: [{ tagName: 'marker' }], want: false }],
    ['mask', { given: [{ tagName: 'mask' }], want: false }],
    ['metadata', { given: [{ tagName: 'metadata' }], want: false }],
    ['mpath', { given: [{ tagName: 'mpath' }], want: false }],
    ['path', { given: [{ tagName: 'path' }], want: false }],
    ['pattern', { given: [{ tagName: 'pattern' }], want: false }],
    ['polygon', { given: [{ tagName: 'polygon' }], want: false }],
    ['polyline', { given: [{ tagName: 'polyline' }], want: false }],
    ['radialGradient', { given: [{ tagName: 'radialGradient' }], want: false }],
    ['rect', { given: [{ tagName: 'rect' }], want: false }],
    ['set', { given: [{ tagName: 'set' }], want: false }],
    ['stop', { given: [{ tagName: 'stop' }], want: false }],
    ['switch', { given: [{ tagName: 'switch' }], want: false }],
    ['symbol', { given: [{ tagName: 'symbol' }], want: false }],
    ['text', { given: [{ tagName: 'text' }], want: false }],
    ['textPath', { given: [{ tagName: 'textPath' }], want: false }],
    ['tspan', { given: [{ tagName: 'tspan' }], want: false }],
    ['use', { given: [{ tagName: 'use' }], want: false }],
    ['view', { given: [{ tagName: 'view' }], want: false }],
  ];

  const testedTags = new Set<string>();

  test.each(tests)('%s', (name, { given, want }) => {
    checkTestAndTagName(name, given[0].tagName);
    testedTags.add(given[0].tagName);
    expect(isInteractive(...given)).toBe(want);
  });

  test('all tags are tested', () => {
    checkAllTagsTested(testedTags);
  });
});
