export * from './is-interactive.js';
export * from './is-name-required.js';
export * from './get-acc-name.js';
export * from './get-elements.js';
export * from './get-required-attributes.js';
export * from './get-role.js';
export * from './get-supported-attributes.js';
export * from './get-supported-roles.js';
export * from './lib/html.js';
export * from './lib/aria-attributes.js';
export * from './lib/aria-roles.js';
export * from './lib/util.js';
export type * from './types.js';
